spring:
  application:
    name: Elasticsearch_spring
  datasource:
    url: jdbc:postgresql://localhost:5432/tz
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  cassandra:
    port: 8080